# Generated by Django 5.1.7 on 2025-03-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categories_category_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categgories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stoks',
            new_name='stock',
        ),
    ]
