# Generated by Django 5.1.7 on 2025-03-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_categgories_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
    ]
